apiVersion: v1
kind: Service
metadata:
  name: quiz-service
  namespace: demoapps
spec:
  selector:
    app: quiz-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      nodePort: 30099
  type: NodePort
