resources:
  - ../../base
  - ingress.yaml
patches:
  - path: deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: quiz-deployment
  - path: service-patch.yaml
    target:
      version: v1
      kind: Service
      name: quiz-service